### ISSUE TITLE
兄弟你的requirements不更新的啊

### ISSUE THREAD

**Issue by Ezra521** [lmx110522/nyist_python_secondmall#1]

**Comment by Ezra521** [comment]
requirements.txt

**Comment by lmx110522** [comment]
这个是我半年前做的项目，这一段时间没有维护，我主要是做JavaWeb的，重心在java上，这个项目有什么不会的，可以联系我，sql一直都忘了上传

**Comment by Ezra521** [comment]
我本人不做web，帮别人做毕设，想改改，你的代码跑不通，难受啊
